[package]
name = "silent_payment_indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.31.1"
leveldb = "0.8.6"
db-key = "0.0.5"
